applications/dashboard/urls.py
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from . import views

app_name = 'dashboard_app'

urlpatterns = [
    path("",views.DashboardView.as_view(), name="index"),
    
    
    ##videos,audios,pdf##
    path('upload/', views.upload_video, name='upload_video'),
    path('catalog/', views.video_catalog, name='video_catalog'),
    path('audio/', views.audio_list, name='audio_list'),
    path('audio/add/', views.add_audio, name='add_audio'),
    path('pdfs/', views.pdf_list, name='pdf_list'),
    path('upload-pdf/', views.upload_pdf, name='upload_pdf'),
    ##videos,audios,pdf##
    
    #path('dashboard/get_nombre_producto/<int:prestamo_id>/', views.GetNombreProductoView.as_view(), name='get_nombre_producto'),
    #path('index/info-prestamo/', views.obtener_informacion_prestamo, name='info_prestamo'),
    #path('dashboard/obtener_detalles_prestamo/', views.ObtenerDetallesPrestamoView.as_view(), name='obtener_detalles_prestamo'),
    
]  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) 

applications/users/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

from . import views

app_name = 'user_app'


urlpatterns = [
    path('registro/', views.RegistrarUsuario.as_view(), name='registro'),
    path('lista-usuarios-generales/',views.ListaUsuariosGeneral.as_view(),name='lista_usuarios_general'),
    path('eliminar-usuarios/<int:pk>/',views.EliminarUsuarios.as_view(),name='eliminar_usuarios'),
    path('editar-usuarios/<int:pk>/',views.EditarUsuario.as_view(),name='editar_usuarios'),
    path('solicitud/<int:user_id>/', views.SolicitudCheck.as_view(), name='solicitud'),
    path('clientes/', views.ClientesAll.as_view(), name='clientes'),
    path('change_password/', views.change_password, name='change_password'),
   

    
]  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) 

yaab_corp/urls.py
from django.contrib import admin
from django.urls import path,include
from django.contrib.auth.views import LoginView,LogoutView
# from yaab_corp.view import index_view
from django.conf import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path("index/", include('applications.dashboard.urls')),
    path("", include('applications.landing.urls')),
    path("users/", include('applications.users.urls')),
    path("otro/", views.index_view, name="index"),
    path('account/login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('accounts/', include('allauth.urls')),
    
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) 

templates/partials/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <title>
      {% block title %}{% endblock title %} | Adminto - Responsive Admin
      Dashboard Template
    </title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta
      content="A fully featured admin theme which can be used to build CRM, CMS, etc."
      name="description"
    />
    <meta content="coderthemes" name="author" />

    <!-- App favicon -->
    <link rel="shortcut icon" href="{% static 'images/favicon.ico' %}" />

    <!-- App css -->

    <link
      href="{% static 'css/app.css' %}"
      rel="stylesheet"
      type="text/css"
      id="app-style"
    />

    <!-- icons -->
    <link
      href="{% static 'css/icons.min.css' %}"
      rel="stylesheet"
      type="text/css"
    />

    {% block css %} {% block extra_css %} {% endblock extra_css %}
    <!---->
    {% include "partials/head-css.html" %} {% endblock css %}
  </head>

  <body
    class="loading"
    data-layout-color="light"
    data-layout-mode="default"
    data-layout-size="fluid"
    data-topbar-color="light"
    data-leftbar-position="fixed"
    data-leftbar-color="light"
    data-leftbar-size="default"
    data-sidebar-user="true"
  >
    <div id="wrapper">
      {% block topbar %} {% endblock topbar %}
      <!---->

      {%include "partials/left-sidebar.html" %}

      <div class="content-page">
        <div class="content">
          <div class="container-fluid">
            {% block content %} {% endblock content %}
          </div>
        </div>
      </div>
    </div>

    {% include "partials/right-sidebar.html" %} {% include
    "partials/vendor.html" %} {% block extra_js %} {% endblock extra_js %}

    <!-- App js-->
    <script src="{% static 'js/app.min.js' %}"></script>
  </body>
</html>

templates/partials/footer.html
<!-- Footer Start -->
<footer class="footer ">
  <div class="container-fluid">
    <div class="row">
      <div class="col-md-6 ">
        <script>
          document.write(new Date().getFullYear());
        </script>
        &copy; tu informacion de tu negocio..
        
        {% comment %} <a class="text-dark" href="{% url 'dashboard_app:terminos_condiciones' %}" target="_blank"> - Aviso de privacidad</a> {% endcomment %}
        <a class="text-dark" href="https://yaab.mx/AvisoDePrivacidad/AvisoDePrivacidad.html" target="_blank"> - Aviso de privacidad</a>
      </div>
      
    </div>
  </div>
</footer>
<!-- end Footer -->

templates/partials/head-css.html
{% load static %}
<!-- App css -->
<link href="{% static 'css/app.min.css' %}" rel="stylesheet" type="text/css" id="app-style" />

<!-- icons -->
<link href="{% static 'css/icons.min.css' %}" rel="stylesheet" type="text/css" />

templates/partials/layout-horizontal.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <title>{% block title %}{% endblock title %} | Adminto - Responsive Admin Dashboard Template</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta content="A fully featured admin theme which can be used to build CRM, CMS, etc." name="description"/>
    <meta content="Coderthemes" name="author"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <!-- App favicon -->
    <link rel="shortcut icon" href="{% static 'images/favicon.ico' %}">

    {% block css %}
        {% block extra_css %} {% endblock extra_css %}
        {% include "partials/head-css.html" %}
    {% endblock css %}
</head>

<body class="loading" data-layout-mode="horizontal" data-layout-color="light" data-layout-size="fluid"
      data-topbar-color="dark" data-leftbar-position="fixed">


<div id="wrapper">

    {% block topbar %}
    {% endblock topbar %}

    {% include "partials/topbar-dark.html" %}
    {% include "partials/horizontal-nav.html" %}

    <div class="content-page">
        <div class="content">

            <div class="container-fluid">
                {% block content %}
                {% endblock content %}
            </div>

        </div>

        {% include "partials/footer.html" %}

    </div>

</div>

{% include "partials/right-sidebar.html" %}

{% include "partials/vendor.html" %}

{% block extra_js %} {% endblock extra_js %}

<!-- App js-->
<script src="{% static 'js/app.min.js' %}"></script>

</body>
</html>

templates/partials/layout-preloader.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <title>{% block title %}{% endblock title %} | Adminto - Responsive Admin Dashboard Template</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta content="A fully featured admin theme which can be used to build CRM, CMS, etc." name="description"/>
    <meta content="Coderthemes" name="author"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <!-- App favicon -->
    <link rel="shortcut icon" href="{% static 'images/favicon.ico' %}">

    {% block css %}
        {% block extra_css %} {% endblock extra_css %}
        {% include "partials/head-css.html" %}
    {% endblock css %}
</head>

<body class="loading" data-layout-color="light" data-layout-mode="default" data-layout-size="fluid"
      data-topbar-color="light" data-leftbar-position="fixed" data-leftbar-color="light" data-leftbar-size='default'
      data-sidebar-user='true'>

        <!-- Pre-loader -->
        <div id="preloader">
            <div id="status">
                <div class="spinner">Loading...</div>
            </div>
        </div>
        <!-- End Preloader-->

<div id="wrapper">

    {% block topbar %}
    {% endblock topbar %}

    {% include "partials/left-sidebar.html" %}

    <div class="content-page">
        <div class="content">

            <div class="container-fluid">
                {% block content %}
                {% endblock content %}
            </div>

        </div>

        {% include "partials/footer.html" %}

    </div>

</div>

{% include "partials/right-sidebar.html" %}

{% include "partials/vendor.html" %}

{% block extra_js %} {% endblock extra_js %}

<!-- App js-->
<script src="{% static 'js/app.min.js' %}"></script>

</body>
</html>

templates/partials/left-sidebar.html
{% load static %}
{% load permissions_tags %}

<style>
  .texto-blanco {
    color: #c5c9cd;
  }

  .texto-blanco:hover {
    color: #ffffff;
  }
  .bgnegro{
    background:#000 !important;
    border-radius: 0% 0% 20% 0% !important;
  }
</style>
<!-- ========== Left Sidebar Start ========== -->
<div class="left-side-menu bgnegro">
  <div class="h-100" data-simplebar>
    <!-- User box -->
    <div class="user-box text-center mb-3">
     {% if user.imagen_perfil %}
        <img
          src="{{ user.imagen_perfil.url }}"
          alt="user-img"
          title="Mat Helme"
          class="rounded-circle img-thumbnail avatar-md"
        />
      {% else %}
       <!-- static 'images/landing/yaab_corp.png'  -->
        <img
          src="{% static 'images/landing/back_3.jpg'%}"
          alt="user-img"
          title="Mat Helme"
          class="rounded-circle img-thumbnail avatar-md"
        />
      {% endif %}

      <div class="dropdown ">
        <a
          href="#"
          class="user-name dropdown-toggle h5 mt-2 mb-1 d-block"
          data-bs-toggle="dropdown"
          aria-expanded="false"
          >{{user.first_name}} {{user.last_name}}</a
        >
        <div class="dropdown-menu user-pro-dropdown mx-auto">
          <!-- item-->
          <a href="javascript:void(0);" class="dropdown-item notify-item d-none">
            <i class="fe-user me-1"></i>
            <span>My Account</span>
          </a>

          <!-- item-->
          <a href="javascript:void(0);" class="dropdown-item notify-item d-none">
            <i class="fe-settings me-1"></i>
            <span>Settings</span>
          </a>

          <!-- item-->
          <a href="javascript:void(0);" class="dropdown-item notify-item d-none">
            <i class="fe-lock me-1"></i>
            <span>Lock Screen</span>
          </a>

          <!-- item-->
          <a href="{% url 'account_logout' %}" class="btn btn-outline-secondary border border-light  notify-item">
            <i class="fe-log-out me-1"></i>
            <span>Cerrar Sesion</span>
          </a>
          <a href="{% url 'user_app:change_password' %}" class="btn btn-outline-secondary border border-light  notify-item">
            <i class="fa fa-lock"></i>
            <span>Cambiar Contraseña</span>
          </a>
        </div>
      </div>

      <p class="text-muted left-user-info">{{user.rfc}}</p>

      <ul class="list-inline d-none">
        <li class="list-inline-item">
          <a href="#" class="text-muted left-user-info">
            <i class="mdi mdi-cog"></i>
          </a>
        </li>

        <li class="list-inline-item">
          <a href="#">
            <i class="mdi mdi-power"></i>
          </a>
        </li>
      </ul>
    </div>

    <!--- Sidemenu -->
    <div id="sidebar-menu">
      <ul id="side-menu">
        
        <li>
          <a href="{% url 'dashboard_app:index' %}">
            <!-- <iconify-icon icon="mdi:view-dashboard"></iconify-icon> -->
            <i class="mdi mdi-home" style="color: #ffff"></i>
            <!-- <span class="badge rounded-pill float-end">9+</span> -->
            <span class="texto-blanco"> Inicio </span>
          </a>
        </li>
        
        
        
        {% if request.user|tiene_permiso:"dashboard.view_prestamo" or request.user|tiene_permiso:"users.view_user" or request.user|tiene_permiso:"dashboard.view_simuladorprueba" or request.user|tiene_permiso:"dashboard.view_credito_cancelado" %}
        <li class="menu-title">Panel de administración</li>
        {% endif %}
        
        {% comment %} {% if permisos.puede_ver_productos %} {% endcomment %}
        {% if request.user|tiene_permiso:"dashboard.view_prestamo" %}
          <li>
            <a href="#sideBarProductos" data-bs-toggle="collapse">
              <i class="mdi mdi-hand-pointing-right" style="color: #ffff"></i>
              <span class="texto-blanco">Contenido </span>
              <span class="menu-arrow" style="color: #ffff"></span>
            </a>
            <div class="collapse" id="sideBarProductos">
              <ul class="nav-second-level">
                
                <li class="d-none">               
                  <a href="{% url 'dashboard_app:upload_video' %}">
                    <span class="texto-blanco">Subir Video</span>
                  </a>
                </li>
                <li>               
                  <a href="{% url 'dashboard_app:video_catalog' %}">
                    <span class="texto-blanco">Videos</span>
                  </a>
                </li>
                <li>               
                  <a href="{% url 'dashboard_app:audio_list' %}">
                    <span class="texto-blanco">Audios</span>
                  </a>
                </li> 
                <li>               
                  <a href="{% url 'dashboard_app:pdf_list' %}">
                    <span class="texto-blanco">Libros</span>
                  </a>
                </li> 
                
                
              </ul>
            </div>
          </li>
        {%endif%}
        
        {% if request.user|tiene_permiso:"users.view_user" %}
        <li>
          <a href="#sideBarUsuarios" data-bs-toggle="collapse">
            <i class="mdi mdi-account-multiple" style="color: #ffff"></i>
            <span class="texto-blanco"> Perfil </span>
            <span class="menu-arrow" style="color: #ffff"></span>
          </a>
          <div class="collapse" id="sideBarUsuarios">
            <ul class="nav-second-level">
              
             

              
              <li class="">
                <!--url 'templates'-->
                <a href="{% url 'user_app:lista_usuarios_general' %}"> <span class="texto-blanco">Editar</span></a>
              </li>
             

              {% if request.user|has_group:"Administrador General" %}
              <li class="">
                <!--url 'templates'-->
                <a href="{% url 'user_app:listar_grupos' %}"> <span class="texto-blanco">Roles</span></a>
              </li>
              {% endif %}
              
              
            </ul>
          </div>
        </li>
        {%endif%}
       

{% comment %}         
        {% if request.user|tiene_permiso:"dashboard.view_simuladorprueba" %}
        <li>
          <a href="#sideBarAdministrativo" data-bs-toggle="collapse">
            <i class="mdi mdi-credit-card-multiple" style="color: #ffff"></i>
            <span class="texto-blanco"> Créditos </span>
            <span class="menu-arrow" style="color: #ffff"></span>
          </a>
          <div class="collapse" id="sideBarAdministrativo">
            <ul class="nav-second-level">
              
              
               <li>
                <!--url 'templates'-->
                <a href="{% url 'user_app:registrar_credito' %}"> <span class="texto-blanco">Registrar crédito</span></a>
              </li>
               <li>
                <!--url 'templates'-->
                <a href="{% url 'credit_personal_app:bandeja_solicitud_html' %}"> <span class="texto-blanco">Autorización de solicitudes</span></a>
              </li>

             

              <li class="">
                <!--url 'estado de cuenta'-->
                <a href="{% url 'calificaciones_app:estado_cuenta_pagos' %}"> <span class="texto-blanco">Estado de cuenta</span></a>
              </li>
              
            </ul>
          </div>
        </li>
        {%endif%}
       
        {% if request.user|tiene_permiso:"dashboard.view_credito_cancelado" %}
        <li>
          <a href="#sideBarCobranza" data-bs-toggle="collapse">
            <i class="mdi mdi-currency-usd" style="color: #ffff"></i>
            <span class="texto-blanco"> Cobranza </span>
            <span class="menu-arrow" style="color: #ffff"></span>
          </a>
          <div class="collapse" id="sideBarCobranza">
            <ul class="nav-second-level">
              

              
              <li >
                <!--url 'templates'-->
                <a href="{% url 'calificaciones_app:estatus_credito' %}"> <span class="texto-blanco">Cuentas por cobrar</span></a>
              </li>
              
              
              <li >
                
                <a href="{% url 'calificaciones_app:notificaciones' %}" > <span class="texto-blanco">Notificaciones</span></a>
              </li>
              <li >
                
                <a href="{% url 'calificaciones_app:creditos_cancelados' %}" > <span class="texto-blanco">Creditos cancelados</span></a>
              </li>
              <li >
               
                <a href="{% url 'calificaciones_app:convenio' %}" > <span class="texto-blanco">Convenios</span></a>
              </li>

              
            </ul>
          </div>
        </li>
        {%endif%}



        <li>
          <a href="#sideBarJuridico" data-bs-toggle="collapse">
            <i class="mdi mdi-currency-usd" style="color: #ffff"></i>
            <span class="texto-blanco"> Jurídico </span>
            <span class="menu-arrow" style="color: #ffff"></span>
          </a>
          <div class="collapse" id="sideBarJuridico">
            <ul class="nav-second-level">
              

              <li >
                <!--url 'tablero BI'-->
                <a href="{% url 'calificaciones_app:cobranza_juridico'  %}"> <span class="texto-blanco">Casos</span></a>
              </li>
              

              
            </ul>
          </div>
        </li>


        <li>
          <a href="#sideBarReportes" data-bs-toggle="collapse">
            <i class="mdi mdi-currency-usd" style="color: #ffff"></i>
            <span class="texto-blanco"> Reportes </span>
            <span class="menu-arrow" style="color: #ffff"></span>
          </a>
          <div class="collapse" id="sideBarReportes">
            <ul class="nav-second-level">
              

              <li >
                <!--url 'tablero BI'-->
                <a href="{% url 'calificaciones_app:vista_reporte_clientes' %}"> <span class="texto-blanco">Cartera</span></a>
              </li>
              

              
            </ul>
          </div>
        </li>


       
        <li>
          <a href="#sideBarConsultas" data-bs-toggle="collapse">
            <i class="mdi mdi-hand-pointing-right" style="color: #ffff"></i>
            <span class="texto-blanco"> Consultas </span>
            <span class="menu-arrow" style="color: #ffff"></span>
          </a>
          <div class="collapse" id="sideBarConsultas">
            <ul class="nav-second-level">

              <li>
                <!--url 'templates'-->
                <a href="{% url 'credit_personal_app:confirmados' %}"> <span class="texto-blanco">Solicitudes</span></a>
              </li>

              <li >
                <!--url 'templates'-->
                <a href="{% url 'calificaciones_app:control_calificaciones' %}"> <span class="texto-blanco">Calificaciones</span></a>
              </li>
              
               <li>
                <!--url 'templates'-->
                <a href="{% url 'calificaciones_app:estatus_credito_estatico' %}"> <span class="texto-blanco">Estatus Creditos</span></a>
              </li>
              
              
            </ul>
          </div>
        </li>
        {% endcomment %}

        
        <li class="menu-title mt-2">General usuarios</li>
       

        <li>
          <a href="#sidebarUsuarios" data-bs-toggle="collapse">
            <i class="mdi mdi-help-circle" style="color: #ffff"></i>
            <span class="texto-blanco"> Ayuda </span>
            <span class="menu-arrow" style="color: #ffff"></span>
          </a>
          <div class="collapse" id="sidebarUsuarios">
            <ul class="nav-second-level">
              <li>
                <!--url 'inbox'-->
                <a href="">
                  <span class="texto-blanco">Preguntas y repuestas</span>
                </a>
              </li>

              
               <li class="d-none">
                <!--url 'templates'-->
                <a href=""> <span class="texto-blanco">Buró de Crédito</span></a>
              </li>
              
              
            </ul>
          </div>
        </li>
      </ul>
    </div>
    <!-- End Sidebar -->

    <div class="clearfix"></div>
  </div>
  <!-- Sidebar -left -->
</div>
<!-- Left Sidebar End -->

templates/partials/title-meta.html
{% load static %}
<meta charset="utf-8" />
<title>{{title}} </title>
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta content="A fully featured admin theme which can be used to build CRM, CMS, etc." name="description" />
<meta content="Coderthemes" name="author" />
<meta http-equiv="X-UA-Compatible" content="IE=edge" />
<!-- App favicon -->
<link rel="shortcut icon" href="{% static 'images/landing/yaab_corp.png' %}">

templates/partials/topbar.html
{% load static %}
<style>
  .bgnegro2{
    background:#000 !important;
    border-radius: 0% 0% 0% 0% !important;
  }
</style>
<!-- Topbar Start -->
<div class="navbar-custom bg">
  <ul class="list-unstyled topnav-menu float-end mb-0">
    <li class="d-none d-lg-block">
      <form class="app-search">
        <div class="app-search-box">
          <!--search para buscar algo -->
          <div class="input-group d-none">
            <input
              type="text"
              class="form-control"
              placeholder="Search..."
              id="top-search"
            />
            <button class="btn input-group-text" type="submit">
              <i class="fe-search"></i>
            </button>
          </div>
          <!--fin search para buscar algo -->
          <div class="dropdown-menu dropdown-lg" id="search-dropdown">
            <!-- item-->
            <div class="dropdown-header noti-title">
              <h5 class="text-overflow mb-2">Found 22 results</h5>
            </div>

            <!-- item-->
            <a href="javascript:void(0);" class="dropdown-item notify-item">
              <i class="fe-home me-1"></i>
              <span>Analytics Report</span>
            </a>

            <!-- item-->
            <a href="javascript:void(0);" class="dropdown-item notify-item">
              <i class="fe-aperture me-1"></i>
              <span>How can I help you?</span>
            </a>

            <!-- item-->
            <a href="javascript:void(0);" class="dropdown-item notify-item">
              <i class="fe-settings me-1"></i>
              <span>User profile settings</span>
            </a>

            <!-- item-->
            <div class="dropdown-header noti-title">
              <h6 class="text-overflow mb-2 text-uppercase">Users</h6>
            </div>

            <div class="notification-list">
              <!-- item-->
              <a href="javascript:void(0);" class="dropdown-item notify-item">
                <div class="d-flex align-items-start">
                  <img
                    class="d-flex me-2 rounded-circle"
                    src="{% static 'images/users/user-2.jpg' %}"
                    alt="Generic placeholder image"
                    height="32"
                  />
                  <div class="w-100">
                    <h5 class="m-0 font-14">Erwin E. Brown</h5>
                    <span class="font-12 mb-0">UI Designer</span>
                  </div>
                </div>
              </a>

              <!-- item-->
              <a href="javascript:void(0);" class="dropdown-item notify-item">
                <div class="d-flex align-items-start">
                  <img
                    class="d-flex me-2 rounded-circle"
                    src="{% static 'images/users/user-5.jpg' %}"
                    alt="Generic placeholder image"
                    height="32"
                  />
                  <div class="w-100">
                    <h5 class="m-0 font-14">Jacob Deo</h5>
                    <span class="font-12 mb-0">Developer</span>
                  </div>
                </div>
              </a>
            </div>
          </div>
        </div>
      </form>
    </li>
    <!--movil-->
    <li class="dropdown d-inline-block d-lg-none d-none">
      <a
        class="nav-link dropdown-toggle arrow-none waves-effect waves-light"
        data-bs-toggle="dropdown"
        href="#"
        role="button"
        aria-haspopup="false"
        aria-expanded="false"
      >
        <i class="fe-search noti-icon "></i>
      </a>
      <div class="dropdown-menu dropdown-lg dropdown-menu-end p-0 ">
        <form class="p-3">
          <input
            type="text"
            class="form-control"
            placeholder="Search ..."
            aria-label="Recipient's username"
          />
        </form>
      </div>
    </li>


    

   
    <li class="dropdown notification-list topbar-dropdown">
      <a
        class="nav-link dropdown-toggle nav-user me-0 waves-effect waves-light"
        data-bs-toggle="dropdown"
        href="#"
        role="button"
        aria-haspopup="false"
        aria-expanded="false"
      >
        
        <span class="pro-user-name ms-1 fw-bold">
          Hola, {{user.first_name}} {{user.last_name}}<i class="mdi mdi-chevron-down"></i>
        </span>
      </a>
      <div class="dropdown-menu dropdown-menu-end profile-dropdown">
        <!-- item-->
        <div class="dropdown-header noti-title d-none">
          <h6 class="text-overflow m-0">Bienvenido !</h6>
        </div>

        <!-- item url 'profile'-->

        <a href="" class="dropdown-item notify-item d-none">
          <i class="fe-user"></i>
          <span>Algo</span>
        </a>

        <!-- item url 'lock-screen'-->
        <!-- <a href="" class="dropdown-item notify-item">
          <i class="fe-lock"></i>
          <span>Lock Screen</span>
        </a> -->

        <div class="dropdown-divider"></div>

        <!-- item url 'logout'   url 'logout'-->
        <a href="{% url 'account_logout' %}" class="dropdown-item notify-item">
          <i class="fe-log-out"></i>
          <span>Cerrar Sesion</span>
        </a>
        <a href="{% url 'user_app:change_password' %}" class="dropdown-item notify-item">
          <i class="fa fa-lock"></i>
          <span>Cambiar Contraseña</span>
        </a>
      </div>
    </li>

    <!--seccion de cambio de template-->
    <li class="dropdown notification-list d-none">
      <a
        href="javascript:void(0);"
        class="nav-link right-bar-toggle waves-effect waves-light"
      >
        <i class="fe-settings noti-icon"></i>
      </a>
    </li>
  </ul>

  <!-- LOGO -->
  <div class="logo-box bgnegro2">
    <a href="{% url 'index' %}" class="logo logo-light text-center">
      <span class="logo-sm">
    
        <img
          src=""
          alt=""
          height="22"
        />
      </span>
      <span class="logo-lg">
       <h3>TU LOGO</h3>
        {% comment %} <img
          src="{% static 'images/landing/yaab_corp.png' %}"
          alt=""
          width="50%"
        /> {% endcomment %}
      </span>
    </a>
    <a href="{% url 'index' %}" class="logo logo-dark text-center">
      <span class="logo-sm">
        <img src="{% static 'images/logo-sm.png' %}" alt="" height="22" />
      </span>
      <span class="logo-lg">
        <img src="{% static 'images/logo-dark.png' %}" alt="" height="16" />
      </span>
    </a>
  </div>

  <ul class="list-unstyled topnav-menu topnav-menu-left mb-0">
    <li>
      <button class="button-menu-mobile disable-btn waves-effect">
        <i class="fe-menu"></i>
      </button>
    </li>

    <li>
      <h4 class="page-title-main">{{ pagetitle }}</h4>
    </li>
  </ul>

  <div class="clearfix"></div>
</div>
<!-- end Topbar -->



    

    
    

templates/partials/vendor.html
{% load static %}
<!-- Vendor -->
<script src="{% static 'libs/jquery/jquery.min.js' %}"></script>
<script src="{% static 'libs/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
<script src="{% static 'libs/simplebar/simplebar.min.js' %}"></script>
<script src="{% static 'libs/node-waves/waves.min.js' %}"></script>
<script src="{% static 'libs/waypoints/lib/jquery.waypoints.min.js' %}"></script>
<script src="{% static 'libs/jquery.counterup/jquery.counterup.min.js' %}"></script>
<script src="{% static 'libs/feather-icons/feather.min.js' %}"></script>