applications/dashboard/urls.py
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from . import views

app_name = 'dashboard_app'

urlpatterns = [
    path("",views.DashboardView.as_view(), name="index"),
    
    
    ##videos,audios,pdf##
    path('upload/', views.upload_video, name='upload_video'),
    path('catalog/', views.video_catalog, name='video_catalog'),
    path('audio/', views.audio_list, name='audio_list'),
    path('audio/add/', views.add_audio, name='add_audio'),
    path('pdfs/', views.pdf_list, name='pdf_list'),
    path('upload-pdf/', views.upload_pdf, name='upload_pdf'),
    ##videos,audios,pdf##
    
    #path('dashboard/get_nombre_producto/<int:prestamo_id>/', views.GetNombreProductoView.as_view(), name='get_nombre_producto'),
    #path('index/info-prestamo/', views.obtener_informacion_prestamo, name='info_prestamo'),
    #path('dashboard/obtener_detalles_prestamo/', views.ObtenerDetallesPrestamoView.as_view(), name='obtener_detalles_prestamo'),
    
]  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) 

applications/landing/urls.py
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from . import views

app_name = 'landing_app'

urlpatterns = [
    path('',views.landing_view, name='landing')
]

yaab_corp/urls.py
from django.contrib import admin
from django.urls import path,include
from django.contrib.auth.views import LoginView,LogoutView
# from yaab_corp.view import index_view
from django.conf import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path("index/", include('applications.dashboard.urls')),
    path("", include('applications.landing.urls')),
    path("users/", include('applications.users.urls')),
    path("otro/", views.index_view, name="index"),
    path('account/login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('accounts/', include('allauth.urls')),
    
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) 

applications/dashboard/models.py
from django.db import models
from decimal import Decimal

from django.db.models.signals import post_save, pre_save
from django.core.mail import send_mail

from django.dispatch import receiver
from django.contrib.auth.models import User
from django.utils import timezone
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
import smtplib
import uuid





        
def send_email(to_email, subject, message):
    from_email = "yaab2023tech@gmail.com"

    msg = MIMEMultipart()
    msg['From'] = from_email
    msg['To'] = to_email
    msg['Subject'] = subject

    msg.attach(MIMEText(message, 'plain'))

    server = smtplib.SMTP('smtp.gmail.com', 587)
    server.starttls()
    server.login(from_email, 'vgit jdxe pgaj ufqy')
    text = msg.as_string()
    server.sendmail(from_email, to_email, text)
    server.quit()
    



class ImageYaab(models.Model):

    top_image = models.ImageField(
        upload_to='solicitud/', blank=True, null=True)

    class Meta:
        verbose_name = 'imagen_yaab'




class VideoProductos(models.Model):
    title = models.CharField(max_length=100,null=True, blank=True)
    url = models.URLField(null=True, blank=True)
    youtube_id = models.CharField(max_length=50,null=True, blank=True)

    def __str__(self):
        return self.title
    
    def save(self, *args, **kwargs):
        # Extraer el ID de YouTube al guardar el modelo
        self.youtube_id = self.extract_youtube_id()
        super(VideoProductos, self).save(*args, **kwargs)
        
    def extract_youtube_id(self):
        import re
        pattern = r'(?:v=|be/)([^&/]+)'
        match = re.search(pattern, self.url)
        if match:
            return match.group(1)
        return None
    
class Audio(models.Model):
    title = models.CharField(max_length=255,blank=True, null=True)
    description = models.TextField(blank=True, null=True)
    image = models.ImageField(upload_to='audio_images/', blank=True, null=True)
    file = models.FileField(upload_to='audio_files/')
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

class PDFDocument(models.Model):
    title = models.CharField(max_length=255,blank=True, null=True)
    file = models.FileField(upload_to='pdfs/')
    image = models.ImageField(upload_to='pdf_images/', blank=True, null=True)
    uploaded_at = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return self.title
    

applications/dashboard/forms.py
from django import forms 
from django.db.models import Min,Max
from .models import VideoProductos,Audio,PDFDocument

from applications.users.models import User

        
class VideoForm(forms.ModelForm):
    class Meta:
        model = VideoProductos
        fields = ['title', 'url']
        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control'}),
            'url': forms.URLInput(attrs={'class': 'form-control'}),
        }
        
class AudioForm(forms.ModelForm):
    class Meta:
        model = Audio
        fields = ['title', 'description', 'image', 'file']
        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control'}),
            'description': forms.Textarea(attrs={'class': 'form-control'}),
            'image': forms.ClearableFileInput(attrs={'class': 'form-control'}),
            'file': forms.ClearableFileInput(attrs={'class': 'form-control'}),
        }  
        
class PDFUploadForm(forms.ModelForm):
    class Meta:
        model = PDFDocument
        fields = ['title', 'file','image']  
        
        
        
        
        
        
        
        
        
   


    

applications/dashboard/views.py
from django.forms import BaseModelForm
from django.contrib import messages
from django.shortcuts import render
from django.contrib.auth.models import Group
from django.contrib.auth.mixins import LoginRequiredMixin,PermissionRequiredMixin
from django.contrib.auth.decorators import permission_required
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_exempt
from django.conf import settings
from django.views import View
from django.views.decorators.http import require_POST,require_GET
from django.db import IntegrityError
from django.http import HttpResponseBadRequest,HttpResponseForbidden, HttpResponse, HttpResponseRedirect, JsonResponse
from django.core.paginator import Paginator

import base64
from django.core.files.base import ContentFile

from django.views.generic import TemplateView
from django.views.generic import ListView,UpdateView,CreateView,DeleteView
from django.shortcuts import render,redirect,get_object_or_404

from django.urls import reverse_lazy,reverse
from django.template.loader import get_template
from django.http import FileResponse
from datetime import datetime
import locale

from .models import ImageYaab,VideoProductos,Audio,PDFDocument
from .forms import VideoForm,AudioForm,PDFUploadForm

from applications.users.models import User
from applications.users.mixins import ValidarPermisosMixin
from applications.users.forms import UserChangeForm

from mifiel import Document, Client

import uuid
import logging



# Create your views here.from django.views.generic.base import TemplateView
class DashboardView(LoginRequiredMixin,ListView):
    model = VideoProductos
    template_name="dashboard/index.html"
    #form_class = SimPruebas #SimuladorForm
    #success_url = reverse_lazy('dashboard_app:index')
    
    def form_valid(self, form):
        # Asignar el usuario logeado al campo usuario_user antes de guardar
        form.instance.usuario_user = self.request.user
        form.instance.registro_creditos = False
        response = super().form_valid(form)
        
        if self.request.headers.get('x-requested-with') == 'XMLHttpRequest':
            return JsonResponse({'success': True})
        else:
            return response


##### videos y audio ######    
def upload_video(request):
    if request.method == 'POST':
        form = VideoForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('dashboard_app:video_catalog')
    else:
        form = VideoForm()
    return render(request, 'dashboard/upload_video.html', {'form': form})  

def video_catalog(request):
    query = request.GET.get('q')
    if query:
        videos = VideoProductos.objects.filter(title__icontains=query)
    else:
        videos = VideoProductos.objects.all().order_by('-id')

    paginator = Paginator(videos, 8)  # 8 videos por página
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    return render(request, 'dashboard/video_catalog.html', {'page_obj': page_obj, 'query': query})

def audio_list(request):
    query = request.GET.get('q', '')
    audios = Audio.objects.all().order_by('-id')
    if query:
        audios = audios.filter(title__icontains=query)
    
    paginator = Paginator(audios, 8)  # 8 audios por página
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    
    return render(request, 'dashboard/audio_catalog.html', {'page_obj': page_obj, 'query': query})

def add_audio(request):
    if request.method == 'POST':
        form = AudioForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('dashboard_app:audio_list')
    else:
        form = AudioForm()
    return render(request, 'dashboard/add_audio.html', {'form': form})
##### videos y audio ######  
def pdf_list(request):
    pdfs = PDFDocument.objects.all()
    return render(request, 'dashboard/pdf_list.html', {'pdfs': pdfs})

def upload_pdf(request):
    if request.method == 'POST':
        form = PDFUploadForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('dashboard_app:pdf_list')
    else:
        form = PDFUploadForm()
    return render(request, 'dashboard/upload_pdf.html', {'form': form})

    
   
        
    
    
    
        
        
        
                
    
    
    
 

templates/dashboard/add_audio.html
{% load static %}
<div class="modal-dialog modal-md">
    <div class="modal-content " style="background-color:black; color:#fff; border-radius: 5% 5% 5% 5% ; box-shadow: 0 4px 30px rgba(8, 8, 8, 0.251);" >
        <div class="modal-header">
            <h4 class="modal-title text-white" id="myModalLabel">Agregua tu audio</h4>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">×</span>
            </button>
        </div> 
        
        <div class='p-3'>
            <form method="POST" action="{% url 'dashboard_app:add_audio'  %}" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-primary">Guardar</button>
            </form>
        </div>
        


    </div>  
</div>

templates/dashboard/audio_catalog.html
{% extends "dashboard/index.html" %}
<!---->
{% load static %}
{% load permissions_tags %}


<!---->
{% block title %}Datatables{% endblock title %}
<!---->
{% block extra_css %}

<!-- third party css -->
<link
  href="{% static 'libs/datatables.net-bs5/css/dataTables.bootstrap5.min.css' %}"
  rel="stylesheet"
  type="text/css"
/>
<link
  href="{% static 'libs/datatables.net-responsive-bs5/css/responsive.bootstrap5.min.css' %}"
  rel="stylesheet"
  type="text/css"
/>
<link
  href="{% static 'libs/datatables.net-buttons-bs5/css/buttons.bootstrap5.min.css' %}"
  rel="stylesheet"
  type="text/css"
/>
<link
  href="{% static 'libs/datatables.net-select-bs5/css//select.bootstrap5.min.css' %}"
  rel="stylesheet"
  type="text/css"
/>
<!-- third party css end -->

{% endblock extra_css %}
<!---->
{% block topbar %}
<!---->
<!---->
{% include "partials/topbar.html" with pagetitle="Videos" %}
<!---->
{% endblock topbar %}
<!---->
{% block content %}

<style>
    .video-thumbnail {
        cursor: pointer;
        transition: transform 0.3s ease; /* Transición suave */
    }

    .video-thumbnail:hover {
        transform: scale(1.1); /* Aumenta el tamaño en un 10% */
    }
 
    .glass-card {
        background: #000000; /* White background with opacity */
        /*border-radius: 15px;  Rounded corners */
        backdrop-filter: blur(10px); /* Blur effect */
        -webkit-backdrop-filter: blur(10px); /* Safari support */
        box-shadow: 0 4px 30px rgba(8, 8, 8, 0.251); /* Light shadow */
        border: 1px solid rgba(255, 255, 255, 0.3); 
        border-radius: 5% ;
    }

    .card-img-top {
        height: 200px; /* Altura fija para la imagen */
        width: 100%; /* Ancho completo del contenedor */
        object-fit: cover; /* La imagen cubre todo el espacio disponible manteniendo el aspecto */
    }
    
</style>

<div class="container mt-2">
    <form method="GET" action="">
        <div class="d-flex justify-content-between">
            <div class="input-group mb-3 w-25">
                <input type="text" name="q" class="form-control" placeholder="Buscar audios..." value="{{ query }}">
                <button class="btn btn-outline-secondary" type="submit">Buscar</button>
            </div>
            <div>
                <button type="button" class="btn btn-outline-secondary btn-sm "  data-bs-toggle="modal" data-bs-target="#subirAudiosModal" onclick="subirAudioModal('{% url 'dashboard_app:add_audio'  %}')">
                    Subir Audio
                </button>
            </div>
        </div>
    </form>
    <div class="row">
        {% for audio in page_obj %}
            <div class="col-md-3">
                <div class="card mb-3 audio-thumbnail glass-card video-thumbnail ">
                    <img src="{{ audio.image.url }}" class="card-img-top " alt="{{ audio.title }}">
                    <div class="card-body m-0 p-0">
                        {% comment %} <h5 class="card-title text-white text-center" style="margin-left:10px;">{{ audio.title }}</h5>
                        <button class="btn btn-outline-secondary btn-sm w-100 play-btn" id="play-btn-{{ audio.id }}" onclick="toggleAudio('{{ audio.file.url }}', '{{ audio.id }}')">Play</button> {% endcomment %}
                        <h5 class="card-title text-white text-center pt-2" style="margin-left:10px;">{{ audio.title }}</h5>
                        <button class="btn btn-outline-secondary btn-sm w-100 play-btn" id="play-btn-{{ audio.id }}" onclick="toggleAudio('{{ audio.file.url }}', '{{ audio.id }}')">Play</button>
                        <button class="btn btn-outline-secondary btn-sm w-100 pause-btn d-none" id="pause-btn-{{ audio.id }}" onclick="pauseAudio('{{ audio.id }}')">Pause</button>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>

    <!-- Paginación -->
    <nav aria-label="Page navigation">
        <ul class="pagination justify-content-center">
            {% if page_obj.has_previous %}
                <li class="page-item">
                    <a class="page-link" href="?page=1{% if query %}&q={{ query }}{% endif %}" aria-label="First">
                        <span aria-hidden="true">&laquo;&laquo;</span>
                    </a>
                </li>
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.previous_page_number }}{% if query %}&q={{ query }}{% endif %}" aria-label="Previous">
                        <span aria-hidden="true">&laquo;</span>
                    </a>
                </li>
            {% endif %}
            {% for num in page_obj.paginator.page_range %}
                {% if page_obj.number == num %}
                    <li class="page-item active"><span class="page-link">{{ num }}</span></li>
                {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
                    <li class="page-item"><a class="page-link" href="?page={{ num }}{% if query %}&q={{ query }}{% endif %}">{{ num }}</a></li>
                {% endif %}
            {% endfor %}
            {% if page_obj.has_next %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.next_page_number }}{% if query %}&q={{ query }}{% endif %}" aria-label="Next">
                        <span aria-hidden="true">&raquo;</span>
                    </a>
                </li>
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}{% if query %}&q={{ query }}{% endif %}" aria-label="Last">
                        <span aria-hidden="true">&raquo;&raquo;</span>
                    </a>
                </li>
            {% endif %}
        </ul>
    </nav>
</div>

<div
  class="modal fade"
  id="subirAudiosModal"
  tabindex="-1"
  role="dialog"
  aria-hidden="true"
>
  <div class="modal-dialog modal-lg"></div>
</div>


{% include "partials/footer.html" %}
<!---->
{% endblock content %}
<!---->
{% block extra_js %}


<!-- third party js -->
<script src="{% static 'libs/datatables.net/js/jquery.dataTables.min.js' %}"></script>
<script src="{% static 'libs/datatables.net-bs5/js/dataTables.bootstrap5.min.js' %}"></script>
<script src="{% static 'libs/datatables.net-responsive/js/dataTables.responsive.min.js' %}"></script>
<script src="{% static 'libs/datatables.net-responsive-bs5/js/responsive.bootstrap5.min.js' %}"></script>
<script src="{% static 'libs/datatables.net-buttons/js/dataTables.buttons.min.js' %}"></script>
<script src="{% static 'libs/datatables.net-buttons-bs5/js/buttons.bootstrap5.min.js' %}"></script>
<script src="{% static 'libs/datatables.net-buttons/js/buttons.html5.min.js' %}"></script>
<script src="{% static 'libs/datatables.net-buttons/js/buttons.flash.min.js' %}"></script>
<script src="{% static 'libs/datatables.net-buttons/js/buttons.print.min.js' %}"></script>
<script src="{% static 'libs/datatables.net-keytable/js/dataTables.keyTable.min.js' %}"></script>
<script src="{% static 'libs/datatables.net-select/js/dataTables.select.min.js' %}"></script>
<script src="{% static 'libs/pdfmake/build/pdfmake.min.js' %}"></script>
<script src="{% static 'libs/pdfmake/build/vfs_fonts.js' %}"></script>
<!-- third party js ends -->

<!-- Datatables init -->
<script src="{% static 'js/pages/datatables.init.js' %}"></script>

<script>
    function subirAudioModal(url) {
        $("#subirAudiosModal").load(url, function () {
          $(this).modal("show");
        });
      }
</script>

<script>
    var currentAudio = null;
    var currentPlayButton = null;
    var currentPauseButton = null;
    
    function toggleAudio(url, id) {
        var playButton = document.getElementById('play-btn-' + id);
        var pauseButton = document.getElementById('pause-btn-' + id);
    
        if (currentAudio && currentAudio.src !== url) {
            currentAudio.pause();
            currentPlayButton.classList.remove('d-none');
            currentPauseButton.classList.add('d-none');
        }
    
        if (!currentAudio || currentAudio.src !== url) {
            currentAudio = new Audio(url);
            currentPlayButton = playButton;
            currentPauseButton = pauseButton;
            currentAudio.play();
            playButton.classList.add('d-none');
            pauseButton.classList.remove('d-none');
        } else if (currentAudio.paused) {
            currentAudio.play();
            playButton.classList.add('d-none');
            pauseButton.classList.remove('d-none');
        } else {
            currentAudio.pause();
            playButton.classList.remove('d-none');
            pauseButton.classList.add('d-none');
        }
    
        currentAudio.onended = function() {
            playButton.classList.remove('d-none');
            pauseButton.classList.add('d-none');
            currentAudio = null;
            currentPlayButton = null;
            currentPauseButton = null;
        };
    }
    
    function pauseAudio(id) {
        if (currentAudio) {
            currentAudio.pause();
            var playButton = document.getElementById('play-btn-' + id);
            var pauseButton = document.getElementById('pause-btn-' + id);
            playButton.classList.remove('d-none');
            pauseButton.classList.add('d-none');
        }
    }
</script>


{% endblock extra_js %}

templates/dashboard/aviso-privacidad.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,400;1,300&display=swap" rel="stylesheet">

    <title>Aviso|Privacidad</title>
</head>

<style>
    body{
        background-color: #EBEFF2;
        font-family: 'Roboto', sans-serif;
    }
</style>
<body>
    <div class="row mx-auto ">
        <div class="col-10 mx-auto ">
            <p class="fw-bolder pt-5" >
                Los titulares de los datos personales tienen el derecho de conocer sobre el tratamiento que se les dará a los datos proporcionados a YAAB, mediante los Avisos de Privacidad que se encuentran en el acceso de cada inmueble de la Institución y a través de los medios electrónicos por los que se recaben datos personales, a fin de que puedan tomar decisiones informadas al respecto.
            </p>

            <h2>
                Conoce los avisos de privacidad de las Unidades de Negocio de YAAB
            </h2>

            <h5>
                Políticas de protección de datos personales
            </h5>
            <br>
            <h5 class="">
                YAAB está comprometido con la protección de los datos personales que le sean proporcionados, en términos de la Ley General de Protección de Datos Personales en Posesión de Sujetos Obligados.

                Por lo anterior, en cumplimiento a la citada Ley, ponemos a disposición nuestros Avisos de Privacidad, a fin de que los titulares de los datos personales conozcan el tratamiento que se dará a los mismos y puedan tomar decisiones informadas al respecto.

                YAAB podrá hacer modificaciones a los Avisos de Privacidad, de las cuales informaremos aquí sobre cualquier cambio, por lo que sugerimos visitar con frecuencia esta área del sitio para informarse con oportunidad.
            </h5>
            <br>

            <h4 class="text-center fw-bold">AVISO DE PRIVACIDAD INTEGRAL</h4>
            <br>
            <h5>
                YAAB con domicilio en Roble, No. 525, colonia Jardines de Irapuato, Irapuato, C.P. 36660, Guanajuato; es el responsable del tratamiento de los datos personales que recabe, los cuales serán salvaguardados de conformidad con la Ley General de Protección de Datos Personales en Posesión de Sujetos Obligados (LGPDPPSO), y demás normatividad que resulte aplicable.
            </h5>
            <br>

            <p class="fw-bolder">¿Cuáles son las finalidades de recabar sus datos personales?</p>
            <p class="fw-bolder">Los datos personales que se recaben serán utilizados con el objeto de:</p>
            <ul class="fw-bolder">
                <li>Poder brindarte los beneficios correspondientes cuando trate de beneficiarios.</li>
                <li>Para el cumplimiento de la relación contractual derivada de la solicitud y/o contratación de nuestros productos o servicios.</li>
                <li>Verificar, confirmar y validar tu identidad.</li>
                <li>Consultar tu historial crediticio.</li>
                <li>Administrar, operar y dar seguimiento a los servicios y productos solicitados o contratados con YAAB.</li>
                <li>Enviarte notificaciones con la información sobre los productos o servicios contratados.</li>
                <li>Realizar gestiones de cobranza.</li>
                <li>Realizar procesos de auditoría interna y externa.</li>
                <li>Comercializar productos y servicios de YAAB. </li>
                <li>Enviarte ofertas, promociones y publicidad de nuestros productos y servicios.</li>
                <li>Contactarte para invitarte a participar en programas, actividades y eventos organizados por YAAB.</li>
                <li>Elaborar perfiles de clientes para ofrecimiento de productos y servicios bancarios y financieros.</li>
                <li>Realizar encuestas.</li>
            </ul>

            <h6>
                Si no deseás que YAAB trate tus datos personales para alguna de las finalidades descritas en este apartado, podrás solicitarlo enviando un correo electrónico a la siguiente dirección: contacto@yaab.mx
            </h6>
            <br>

            <h5 class="text-dark">¿Qué datos personales se recaban?</h5>
            <h5>
                Para cumplir con las finalidades previstas en el presente Aviso de Privacidad, YAAB recabará la siguiente información:
            </h5>

            <ul>
                <li>Datos de identificación, incluyendo tu imagen.</li>
                <li>Datos de contacto.</li>
                <li>Datos de ubicación.</li>
                <li>Datos laborales.</li>
                <li>Datos académicos.</li>
                <li>Datos patrimoniales y/o financieros.</li>
                <li>Datos biométricos.</li>
            </ul>

            <h4 class="fw-bolder">Transferencia de datos personales </h4>
            <br>
            <h6>
                YAAB podrá transferir tus datos personales tanto a entidades nacionales como extranjeras, sin requerir tu consentimiento en los siguientes supuestos:
            </h6>
            <ul>
                <li>A sociedades de información crediticia para cumplir con obligaciones derivadas de la relación jurídica entre tú y YAAB.</li>
                <li>A autoridades competentes, en ejercicio de sus atribuciones y que estén debidamente fundados y motivados.</li>
                <li>A empresas de mensajería para el envío de comunicaciones relacionadas con los productos y/o servicios contratados.</li>
                <li>A instituciones financieras a efecto de cumplir con la portabilidad y/o movilidad de productos financieros.</li>
            </ul>

            <h6>
                De igual forma, podrán transferirse sus datos personales sin necesidad de requerir el consentimiento de la persona titular, bajo los supuestos establecidos en los artículos 22 y 70 de la LGPDPPSO.
            </h6>
            <h6 class="">Mecanismos, medios y procedimientos disponibles para ejercer los derechos ARCO. </h6>

            <h6>
                Usted puede ejercer sus derechos de acceso, rectificación, cancelación y oposición de datos personales mediante solicitud presentada por los siguientes medios:
            </h6>
            <h6>
                Por correo electrónico en la dirección: contacto@yaab.mx
            </h6>
            <br>
            <h4 class="fw-bolder">Cambios y actualizaciones al Aviso de Privacidad. </h4>
            <h6>
                En caso de que exista un cambio o actualización en el Aviso de Privacidad se pondrá a su disposición en esta misma dirección electrónica: 
            </h6>

            <a href="{% url 'landing_app:landing' %}" target="_blank" style="text-decoration: none; color:black;"> https://www.yaab.mx. </a>
            <br>
            <br>
            <h6>
                No obstante, el aviso de privacidad siempre deberá observar las disposiciones jurídicas aplicables.
            </h6>
            <br><br>

            <h4 class="text-end pb-4 fw-bolder" >
                Fecha de actualización: noviembre 2023
            </h4>


            
        </div>
    </div>


    
    
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
</body>
</html>






     
    

templates/dashboard/upload_pdf.html
{% load static %}
<div class="modal-dialog modal-md">
    <div class="modal-content " style="background-color:black; color:#fff; border-radius: 5% 5% 5% 5% ; box-shadow: 0 4px 30px rgba(8, 8, 8, 0.251);" >
        <div class="modal-header">
            <h4 class="modal-title text-white" id="myModalLabel">Agregua tu audio</h4>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">×</span>
            </button>
        </div> 
        
        <div class='p-3'>
            <form method="POST" action="{% url 'dashboard_app:upload_pdf'  %}" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-primary">Guardar</button>
            </form>
        </div>
        


    </div>  
</div>