applications/landing/urls.py
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from . import views

app_name = 'landing_app'

urlpatterns = [
    path('',views.landing_view, name='landing')
]

applications/users/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

from . import views

app_name = 'user_app'


urlpatterns = [
    path('registro/', views.RegistrarUsuario.as_view(), name='registro'),
    path('lista-usuarios-generales/',views.ListaUsuariosGeneral.as_view(),name='lista_usuarios_general'),
    path('eliminar-usuarios/<int:pk>/',views.EliminarUsuarios.as_view(),name='eliminar_usuarios'),
    path('editar-usuarios/<int:pk>/',views.EditarUsuario.as_view(),name='editar_usuarios'),
    path('solicitud/<int:user_id>/', views.SolicitudCheck.as_view(), name='solicitud'),
    path('clientes/', views.ClientesAll.as_view(), name='clientes'),
    path('change_password/', views.change_password, name='change_password'),
   

    
]  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) 

yaab_corp/urls.py
from django.contrib import admin
from django.urls import path,include
from django.contrib.auth.views import LoginView,LogoutView
# from yaab_corp.view import index_view
from django.conf import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path("index/", include('applications.dashboard.urls')),
    path("", include('applications.landing.urls')),
    path("users/", include('applications.users.urls')),
    path("otro/", views.index_view, name="index"),
    path('account/login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('accounts/', include('allauth.urls')),
    
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) 

applications/users/models.py
from django.db.models.signals import post_save,pre_save
from django.dispatch import receiver
from django.shortcuts import render
from django.contrib.auth.models import Group
from django.contrib.contenttypes.models import ContentType
from django.urls import reverse

from django.db import models
from django.utils.translation import gettext_lazy as _
from django.contrib.auth.models import AbstractUser
from django.utils import timezone
from datetime import timedelta,datetime


class User(AbstractUser):
    
    # *************datos personales ***********
    email = models.EmailField(_('enmail adrees'),unique=True)
    username = models.CharField(max_length=150, unique=False, blank=True, null=True)
    password = models.CharField(_('password'), max_length=128,blank=True,null=True)
    edad=models.IntegerField(null=True,blank=True)
    first_name = models.CharField(max_length=30)
    imagen_perfil = models.ImageField(upload_to='perfil/',blank=True,null=True)
    last_name = models.CharField(max_length=30)
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)
    date_joined = models.DateTimeField(default=timezone.now)
    second_name = models.CharField(max_length=30,blank=True,null=True)
    fecha_nac = models.DateField(null=True,blank=True)   
    telefono_particular = models.CharField(max_length=100,blank=True,null=True)
    facebook = models.CharField(max_length=150, unique=False, blank=True, null=True)
    gmail = models.CharField(max_length=150,blank=True, null=True)
    twitter = models.CharField(max_length=150,blank=True, null=True)
    github = models.CharField(max_length=150,blank=True, null=True)
    descripcion = models.TextField(blank=True, null=True)
    
    
    
   
    
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username']
    
    def __str__(self):
        return  self.first_name + ' ' + self.last_name + ' - ' + self.email  + ' ' + str(self.id)
    


    

    
    

        
    

applications/users/forms.py
from django.forms import ModelForm, widgets
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.utils.safestring import mark_safe
from django.template.loader import render_to_string
from django.contrib.auth.models import User, Group
from datetime import datetime
from .models import User
from django.utils.translation import gettext_lazy as _


# class SignaturePadWidget(forms.widgets.Widget):
#     template_name = 'users/widgets/signature_pad_widget.html'


#     class Media:
#         js = ('https://cdn.jsdelivr.net/npm/signature_pad@2.3.2/signature_pad.js',)

# class SignaturePadFormField(forms.CharField):
#     widget = SignaturePadWidget

class AdminUserCreationForm(UserCreationForm):
    email = forms.EmailField(
        label="Email",
        widget=forms.EmailInput(
            attrs={
                # h-75 rounded-pill ml-1
                'class': 'form-control ',
                'type': 'email',
                'placeholder': 'usuario@ejemplo.com',

            }
        )
    )

    username = forms.CharField(
        max_length=50,
        label="Usuario",

        widget=forms.TextInput(
            attrs={
                'class': 'form-control ',
                'placeholder': 'Usuario...',

            }
        )
    )

    password1 = forms.CharField(
        max_length=50,
        label="Contraseña",
        widget=forms.PasswordInput(
            attrs={
                'class': 'form-control ',
                'placeholder': 'Contraseña',

            }
        )
    )

    password2 = forms.CharField(
        max_length=50,
        label="Confirmar contraseña",
        widget=forms.PasswordInput(
            attrs={
                'class': 'form-control ',
                'placeholder': 'Confirmar contraseña',

            }
        )
    )

    validate_email = forms.BooleanField(
        label='',
        required=False,
        widget=forms.CheckboxInput(
            attrs={
                'class' : 'd-none'
            }
        )
    
    )

    class Meta:

        model = User
        fields = ('email', 'username', 'password1',
                  'password2', 'validate_email')

    def save(self, commit=True):
        user = super().save(commit=False)
        if not self.cleaned_data['validate_email']:
            user.is_active = True
        if commit:
            user.save()
        return user


class UserCreationForm(forms.ModelForm):
    # Define los campos que deseas incluir en el formulario

    email = forms.EmailField(
        label="Email",

        widget=forms.EmailInput(
            attrs={
                # h-75 rounded-pill ml-1
                'class': 'form-control ',
                'type': 'email',
                'placeholder': 'usuario@ejemplo.com',

            }
        )
    )

    password1 = forms.CharField(
        max_length=50,
        label="Contraseña",
        widget=forms.PasswordInput(
            attrs={
                'class': 'form-control ',
                'placeholder': 'contraseña',

            }
        )
    )

    password2 = forms.CharField(
        max_length=50,
        label="Contraseña",

        widget=forms.PasswordInput(
            attrs={
                'class': 'form-control ',
                'placeholder': 'confirmar contraseña...',

            }
        )
    )

    first_name = forms.CharField(
        max_length=50,
        label="Usuario",

        widget=forms.TextInput(
            attrs={
                'class': 'form-control ',
                'placeholder': 'nombres...',

            }
        )
    )

    last_name = forms.CharField(
        max_length=50,
        label="Usuario",

        widget=forms.TextInput(
            attrs={
                'class': 'form-control ',
                'placeholder': 'primer apellido...',

            }
        )
    )

    second_name = forms.CharField(
        max_length=50,
        label="Usuario",

        widget=forms.TextInput(
            attrs={
                'class': 'form-control ',
                'placeholder': 'segundo apellido...',

            }
        )
    )

    class Meta:
        model = User
        fields = ('email', 'password1', 'password2',
                  'first_name', 'last_name', 'second_name')


class UserChangeForm(forms.ModelForm):

    email = forms.CharField(
        max_length=50,
        label="Usuario",
        required=False,
        widget=forms.TextInput(
            attrs={
                'class': 'form-control ',
                'placeholder': 'Usuario...',

            }
        )
    )

    first_name = forms.CharField(
        max_length=50,
        label="Nombre",
        required=False,
        widget=forms.TextInput(
            attrs={
                'class': 'form-control ',
                'placeholder': 'Nombre...',

            }
        )
    )

    last_name = forms.CharField(
        max_length=50,
        label="Apellido",
        required=False,
        widget=forms.TextInput(
            attrs={
                'class': 'form-control ',
                'placeholder': 'Apellido...',

            }
        )
    )

    second_name = forms.CharField(
        max_length=50,
        label="Segundo Apellido",
        required=True,
        widget=forms.TextInput(
            attrs={
                'id': 'id_second_name',
                'class': 'form-control ',
                'placeholder': 'Apellido...',

            }
        )
    )

    telefono_particular = forms.CharField(
        max_length=50,
        label="Teléfono particular",
        required=False,
        widget=forms.TextInput(
            attrs={
                'class': 'form-control ',
                'placeholder': 'Teléfono...',

            }
        )
    )

    fecha_nac = forms.DateField(
        required=False,
        widget=forms.DateInput(
            attrs={
                'id': 'id_fecha_nac',
                'class': 'form-control',
                'type': 'text',
                'placeholder': 'ingresa tu fecha de nacimiento'

            }
        )

    )


    imagen_perfil = forms.ImageField(
        required=False,
        label='Imagen de Perfil',
        widget=forms.FileInput(
            attrs={
                'class': 'form-control'
            }
        )
    )
    
    facebook = forms.CharField(
        max_length=50,
        label="Ingresa tu link de facebook",
        required=False,
        widget=forms.TextInput(
            attrs={
                'class': 'form-control ',
                'placeholder': 'URL...',

            }
        )
    )
    
    gmail = forms.CharField(
        max_length=50,
        label="Ingresa tu link de gmail",
        required=False,
        widget=forms.TextInput(
            attrs={
                'class': 'form-control ',
                'placeholder': 'URL...',

            }
        )
    )
    twitter = forms.CharField(
        max_length=50,
        label="Ingresa tu link de twitter",
        required=False,
        widget=forms.TextInput(
            attrs={
                'class': 'form-control ',
                'placeholder': 'URL...',

            }
        )
    )
    github = forms.CharField(
        max_length=50,
        label="Ingresa tu link de github",
        required=False,
        widget=forms.TextInput(
            attrs={
                'class': 'form-control ',
                'placeholder': 'URL...',

            }
        )
    )
    
    descripcion = forms.CharField(
        label="Incluye una breve descripción de ti: ",
        required=False,
        widget=forms.TextInput(
            attrs={
                'class': 'form-control mb-2',
                'placeholder': 'descripción...',

            }
        )
    )
    

    

    class Meta:
        model = User
        fields = ('email', 'first_name', 'last_name', 'second_name', 'fecha_nac', 'telefono_particular','imagen_perfil','facebook','gmail','twitter','github','descripcion')



class AsignarRolForm(forms.Form):
    usuario = forms.ModelChoiceField(queryset=User.objects.all(), label="Usuario")
    grupo = forms.ModelChoiceField(queryset=Group.objects.all(), label="Grupo")

applications/users/views.py
from django.shortcuts import render, redirect, get_object_or_404

from django.urls import reverse_lazy, reverse
from django.contrib.auth import get_user_model
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.contrib.auth.hashers import make_password
from allauth.account.views import SignupView

import base64
from django.core.files.base import ContentFile
from PIL import Image
from io import BytesIO
from django.http import JsonResponse, HttpResponse, HttpResponseRedirect
from django.core.mail import send_mail, BadHeaderError
from django.utils import timezone
import os
from django.conf import settings
from django.views.generic.edit import FormView
from django.views.generic import View, TemplateView, ListView, UpdateView, CreateView, DeleteView


from .mixins import ValidarPermisosMixin
from .models import User
from .forms import UserCreationForm, UserChangeForm,  AdminUserCreationForm,  AsignarRolForm

from django.contrib.contenttypes.models import ContentType
from django.contrib.auth.models import  Group
from django.contrib.auth.models import Permission
from django.contrib.auth.decorators import permission_required
from django.views.decorators.http import require_http_methods

import uuid
from django.db.models import Q


import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
# Create your views here.


class AdminRegisterView(FormView):
    template_name = 'users/listar-usuarios.html'
    form_class = AdminUserCreationForm
    success_url = reverse_lazy('lista_usuarios')

    def form_valid(self, form):
        # Guardar el formulario y redirigir al éxito si es válido
        form.save()
        return super().form_valid(form)




class RegistrarUsuario(CreateView):
    model = User
    template_name = 'users/register.html'
    form_class = UserCreationForm
    success_url = reverse_lazy('login')

    def form_valid(self, form):
        # Obtenemos los datos del formulario
        email = form.cleaned_data['email']
        password = form.cleaned_data['password1']  # Obtenemos la contraseña

        # Creamos una instancia del modelo de usuario pero no la guardamos aún
        user = form.save(commit=False)
        # Usamos make_password para cifrar la contraseña antes de guardarla
        user.password = make_password(password)
        user.save()
        return super().form_valid(form)

class EditarUsuario(UpdateView):
    model = User
    template_name = 'users/editar-usuario.html'
    form_class = UserChangeForm
    success_url = reverse_lazy('user_app:lista_usuarios_general')


class EliminarUsuarios(DeleteView):
    model = User
    template_name = 'users/eliminar-usuario.html'
    success_url = reverse_lazy('user_app:lista_usuarios_general')


    

class ListaUsuariosGeneral(FormView, ListView):
    template_name = 'users/listar-usuarios-clientes.html'
    context_object_name = 'lista'
    form_class = AdminUserCreationForm
    success_url = reverse_lazy('user_app:lista_usuarios_general')

    def get_queryset(self):
        # usuarios_admin = User.objects.filter(groups__name='Administrador General').order_by('-date_joined')
        # usuarios_cobranza = User.objects.filter(groups__name='Cobranza').order_by('-date_joined')
        # usuarios_trabajadores = usuarios_admin.union(usuarios_cobranza)
        # usuarios_sin_grupo = User.objects.exclude(id__in=usuarios_trabajadores.values_list('id', flat=True))
        #return usuarios_sin_grupo
        return User.objects.filter(id=self.request.user.id)

    def form_valid(self, form):
        # Guardar el formulario y redirigir al éxito si es válido
        form.save()
        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = self.get_form()
        context['allUser'] = User.objects.all()
        return context

class SolicitudCheck(View):
    def post(self, request, user_id):
        try:
            user = User.objects.get(pk=user_id)
            user.solicitud = True
            user.save()
            return JsonResponse({'message': 'Solicitud marcada como true'})

        except User.DoesNotExist:
            return JsonResponse({'message': 'Solicitud no encontrada'}, status=404)


class ClientesAll(ListView):
    template_name = 'users/clientes.html'
    context_object_name = 'clientes'

    def get_queryset(self):

        cliente = User.objects.filter(solicitud=True)

        return cliente


class RegistrarUsuario(CreateView):
    model = User
    template_name = 'users/register.html'
    form_class = UserCreationForm
    success_url = reverse_lazy('login')

@login_required
def change_password(request):
    if request.method == 'POST':
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)  # Actualizar la sesión del usuario para mantener la sesión iniciada
            messages.success(request, 'Tu contraseña ha sido cambiada exitosamente.')
            return redirect('dashboard_app:index')  # Redirigir a la página de perfil o donde desees después de cambiar la contraseña
        else:
            messages.error(request, 'Por favor, corrige los errores.')
    else:
        form = PasswordChangeForm(request.user)
 
    return render(request, 'users/change_password.html', {'form': form})

templates/users/change_password.html
{% extends "dashboard/index.html" %}
<!---->
{% load static %}


{% block content %}

    <h2>Cambio de Contraseña</h2>
    <form method="post" class="form-control pt-3">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-outline-secondary btn-sm border">Guardar Cambios</button>
    </form>


{% endblock content %}

templates/users/editar-usuario.html
{% load static %}
  <div class="modal-dialog modal-md">
    <div class="modal-content" style="background-color:black; color:#fff; border-radius: 5% 5% 5% 5% ; box-shadow: 0 4px 30px rgba(8, 8, 8, 0.251);">
      <div class="modal-header">
        <h4 class="modal-title text-white" id="myModalLabel">Editar Usuario</h4>
        <button type="button" class="close" data-bs-dismiss="modal">
          <span aria-hidden="true">×</span>
        </button>
      </div>   

      
      <form
        method="POST"
        enctype="multipart/form-data"
        action="{% url 'user_app:editar_usuarios' object.id %}"
      >
        {% csrf_token %}
        <div class="modal-body">

            

            <div class="tab-content mt-2">
                <div class="tab-pane fade active show mt-1" id="datos_personales">

                    <div class="row ">
                         
                        <div class="col mb-3">                            
                            <label for="email">Usuario:</label>                            
                                {{form.email}}                           
                        </div>

                        <div class="col mb-3">
                             <label  for="first-name">Nombre:  </label>
                              {{form.first_name}}
                        </div>
                                          
                    </div>

                    <div class="row">

                         
                        <div class="col  mb-3">                            
                            <label  for="second-name">Apellido:</label>
                            {{form.last_name}}                                
                        </div>

                        <div class="col  mb-3">                            
                            <label for="first-name">Apellido:</label>
                                {{form.second_name}}                                
                        </div>
                    </div>

                    <div class="row ">
                        
                        <div class="col  mb-3">
                            <label for="first-name">Fecha Nac. : </label>
                            {{form.fecha_nac}}
                        </div>

                        <div class="col  mb-3">
                            <label for="first-name">Teléfono particular: </label>
                            {{form.telefono_particular}}                             
                        </div>

                    </div>
                    
                    <div class="row ">                    
                        <div class="col  mb-3 ">                            
                            <label for="first-name">Facebook:
                            </label>                            
                            {{form.facebook}}                        
                        </div>
                        <div class="col  mb-3 ">                            
                            <label for="first-name">Foto Perfil:
                            </label>                            
                            {{form.imagen_perfil}}                        
                        </div>
                    </div>
                    <div class="row ">
                        <div class="col  mb-3 ">                            
                            <label for="first-name">Gmail:
                            </label>                            
                            {{form.gmail}}                        
                        </div>
                        <div class="col  mb-3 ">                            
                            <label for="first-name">Twitter:
                            </label>                            
                            {{form.twitter}}                        
                        </div>                    
                    </div>
                    <div class="row ">
                        <div class="col  mb-3 ">                            
                            <label for="first-name">GitHub:
                            </label>                            
                            {{form.github}}                        
                        </div>
                        <div class="col  mb-3 ">                            
                            <label for="first-name">Descripción:
                            </label>                            
                            {{form.descripcion}}                        
                        </div>
                    </div>
                    

                </div>

               

            </div>
         

          

          <div class="modal-footer">
             

            <button
              type="button"
              class="btn btn-outline-secondary btn-sm"
              data-bs-dismiss="modal"
            >
              Cerrar
            </button>
           
            <button type="submit" class="btn btn-outline-secondary btn-sm">
              Actualizar Usuario
            </button>
          </div>
        </div>
      </form>
    </div>
  </div>
</div>

templates/users/listar-usuarios-clientes.html
{% extends "dashboard/index.html" %}
<!---->
{% load static %}
{% load permissions_tags %}

<!---->
{% block title %}Datatables{% endblock title %}
<!---->
{% block extra_css %}

<!-- third party css -->
<link
  href="{% static 'libs/datatables.net-bs5/css/dataTables.bootstrap5.min.css' %}"
  rel="stylesheet"
  type="text/css"
/>
<link
  href="{% static 'libs/datatables.net-responsive-bs5/css/responsive.bootstrap5.min.css' %}"
  rel="stylesheet"
  type="text/css"
/>
<link
  href="{% static 'libs/datatables.net-buttons-bs5/css/buttons.bootstrap5.min.css' %}"
  rel="stylesheet"
  type="text/css"
/>
<link
  href="{% static 'libs/datatables.net-select-bs5/css//select.bootstrap5.min.css' %}"
  rel="stylesheet"
  type="text/css"
/>
<!-- third party css end -->

{% endblock extra_css %}
<!---->
{% block topbar %}
<!---->
<!---->
{% include "partials/topbar.html" with pagetitle="Perfil" %}
<!---->
{% endblock topbar %}
<!---->
{% block content %}

<style>
  .glass-card {
    background: #000000; /* White background with opacity */
    /*border-radius: 15px;  Rounded corners */
    backdrop-filter: blur(10px); /* Blur effect */
    -webkit-backdrop-filter: blur(10px); /* Safari support */
    box-shadow: 0 4px 30px rgba(8, 8, 8, 0.251); /* Light shadow */
    border: 1px solid rgba(255, 255, 255, 0.3); /* Light border */
    border-radius: 5% 5% 5% 5% 
  }
</style>



<!--productos-->
<div class="row">

  <div class="card glass-card">
    <div class="bg-picture card-body">
        <div class="text-center">
            {% if user.imagen_perfil %}
                <img src="{{ user.imagen_perfil.url }}" alt="user-img" title="Mat Helme" class="rounded-circle img-thumbnail avatar-lg" />
            {% else %}
                <img src="{% static 'images/landing/back_3.jpg'%}" alt="user-img" title="Mat Helme" class="rounded-circle img-thumbnail avatar-md" />
            {% endif %}
        </div>
        <div class="text-center mt-3">
            <h4 class="m-0 text-white">{{ user.first_name | upper }} {{ user.last_name | upper }}</h4>
            <p class="text-muted"><i>Web Designer</i></p>
            <p class="font-13">{{ user.descripcion }}</p>
            <ul class="social-list list-inline mt-3 mb-0">
                <li class="list-inline-item">
                    <a href="{{ user.facebook }}" class="social-list-item border-purple text-purple"><i class="mdi mdi-facebook"></i></a>
                </li>
                <li class="list-inline-item">
                    <a href="{{ user.gmail }}" class="social-list-item border-danger text-danger"><i class="mdi mdi-google"></i></a>
                </li>
                <li class="list-inline-item">
                    <a href="{{ user.twitter }}" class="social-list-item border-info text-info"><i class="mdi mdi-twitter"></i></a>
                </li>
                <li class="list-inline-item">
                    <a href="{{ user.github }}" class="social-list-item border-secondary text-secondary"><i class="mdi mdi-github"></i></a>
                </li>
                <li class="list-inline-item">
                    {% for item in lista %}
                        <button type="button" class="btn btn-outline-secondary btn-sm rounded-pill" data-bs-toggle="modal" data-bs-target="#actualizarUsuariosModal" onclick="actualizarModalUser('{% url 'user_app:editar_usuarios' pk=item.id %}')">
                            Editar Perfil
                        </button>
                    {% endfor %}
                </li>
            </ul>
        </div>
        <div class="mt-3">
          <h5 class="text-white">"Si eres administrador puedes ver la tabla."</h5>
            <table id="datatable" class="table dt-responsive nowrap" style="background-color:black; color:#fff;">
                <thead>
                    <tr>
                        <th>Usuario</th>
                        <th>Nombre</th>
                        <th>Apellido Paterno</th>
                        <th>Apellido Materno</th>
                        <th>Acciones</th>
                    </tr>
                </thead>
                <tbody>
                    {% for item in allUser %}
                        <tr>
                            <td>{{ item.email }}</td>
                            <td>{{ item.first_name | upper }}</td>
                            <td>{{ item.last_name | upper }}</td>
                            <td>{{ item.second_name | upper }}</td>
                            <td>
                                <div class="dropdown">
                                    <a class="dropdown-toggle" type="button" id="dropdownMenuButton" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                        <i class="mdi mdi-playlist-plus" style="color: white; font-size:18px;"></i>
                                    </a>
                                    <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                                        <button type="button" class="btn btn-outline-secondary btn-sm" data-bs-toggle="modal" data-bs-target="#actualizarUsuariosModal" onclick="actualizarModalUser('{% url 'user_app:editar_usuarios' pk=item.id %}')">
                                            Editar
                                        </button>
                                        <button type="button" class="btn btn-outline-secondary btn-sm" data-bs-toggle="modal" data-bs-target="#eliminarUsuarioModal" onclick="eliminarModalUser('{% url 'user_app:eliminar_usuarios' pk=item.pk %}')">
                                            Eliminar
                                        </button>
                                    </div>
                                </div>
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
              </table>
        </div>
    </div>   
  </div> 
</div>





<!--modal eliminar usuarios-->
<div
  class="modal fade"
  id="eliminarUsuarioModal"
  tabindex="-1"
  role="dialog"
  aria-hidden="true"
>
  <div class="modal-dialog modal-lg"></div>
</div>
<!--modal eliminar usuarios-->

<!--modal editar usuarios-->
<div
  class="modal fade"
  id="actualizarUsuariosModal"
  tabindex="-1"
  role="dialog"
  aria-hidden="true"
>
  <div class="modal-dialog modal-lg"></div>
</div>
<!--modal editar usuarios-->



{% include "partials/footer.html" %}
<!---->
{% endblock content %}
<!---->
{% block extra_js %}

<script>
  //eliminar usuario
  function eliminarModalUser(url) {
    $("#eliminarUsuarioModal").load(url, function () {
      $(this).modal("show");
    });
  }
  //editar usuario
  function actualizarModalUser(url) {
    $("#actualizarUsuariosModal").load(url, function () {
      $(this).modal("show");
    });
  }
  

</script>

<!-- third party js -->
<script src="{% static 'libs/datatables.net/js/jquery.dataTables.min.js' %}"></script>
<script src="{% static 'libs/datatables.net-bs5/js/dataTables.bootstrap5.min.js' %}"></script>
<script src="{% static 'libs/datatables.net-responsive/js/dataTables.responsive.min.js' %}"></script>
<script src="{% static 'libs/datatables.net-responsive-bs5/js/responsive.bootstrap5.min.js' %}"></script>
<script src="{% static 'libs/datatables.net-buttons/js/dataTables.buttons.min.js' %}"></script>
<script src="{% static 'libs/datatables.net-buttons-bs5/js/buttons.bootstrap5.min.js' %}"></script>
<script src="{% static 'libs/datatables.net-buttons/js/buttons.html5.min.js' %}"></script>
<script src="{% static 'libs/datatables.net-buttons/js/buttons.flash.min.js' %}"></script>
<script src="{% static 'libs/datatables.net-buttons/js/buttons.print.min.js' %}"></script>
<script src="{% static 'libs/datatables.net-keytable/js/dataTables.keyTable.min.js' %}"></script>
<script src="{% static 'libs/datatables.net-select/js/dataTables.select.min.js' %}"></script>
<script src="{% static 'libs/pdfmake/build/pdfmake.min.js' %}"></script>
<script src="{% static 'libs/pdfmake/build/vfs_fonts.js' %}"></script>
<!-- third party js ends -->

<!-- Datatables init -->
<script src="{% static 'js/pages/datatables.init.js' %}"></script>

<!---->


{% endblock extra_js %}